// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs_L8i5CbvURZKIfvIFDWIaTTV1VdBKEE',
    appId: '1:979276465695:android:888f4bd4f53598d145372a',
    messagingSenderId: '979276465695',
    projectId: 'interviewtask-38327',
    storageBucket: 'interviewtask-38327.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAopKMFISc4iUOF6eQaf-xJgF0Z0eyAO7I',
    appId: '1:979276465695:ios:5d937c1f235ecf0b45372a',
    messagingSenderId: '979276465695',
    projectId: 'interviewtask-38327',
    storageBucket: 'interviewtask-38327.firebasestorage.app',
    iosBundleId: 'com.example.interviewTask',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYfxHUCEq09GuWABje1SUKeEXxdIVVdUA',
    appId: '1:979276465695:web:5597c64d4fe081a045372a',
    messagingSenderId: '979276465695',
    projectId: 'interviewtask-38327',
    authDomain: 'interviewtask-38327.firebaseapp.com',
    storageBucket: 'interviewtask-38327.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAopKMFISc4iUOF6eQaf-xJgF0Z0eyAO7I',
    appId: '1:979276465695:ios:5d937c1f235ecf0b45372a',
    messagingSenderId: '979276465695',
    projectId: 'interviewtask-38327',
    storageBucket: 'interviewtask-38327.firebasestorage.app',
    iosBundleId: 'com.example.interviewTask',
  );

}